// AUTOCOMPLETE LOCATIONS
export const SEARCH_LOCATIONS_INIT = "SEARCH_LOCATIONS_INIT";
export const SEARCH_RESET = "SEARCH_RESET";
export const SEARCH_LOCATIONS_SUCCESS = "SEARCH_LOCATIONS_SUCCESS";
export const SEARCH_LOCATIONS_FAIL = "SEARCH_LOCATIONS_FAIL";

// CURRENT LOCATION
export const CURRENT_LOCATION_INIT = "CURRENT_LOCATION_INIT";
export const CURRENT_LOCATION_SUCCESS = "CURRENT_LOCATION_SUCCESS";
export const SET_CURRENT_LOCATION = "SET_CURRENT_LOCATION";
export const CURRENT_LOCATION_FAIL = "CURRENT_LOCATION_FAIL";

// FORECASTS
export const GET_FORECASTS_INIT = "GET_FORECASTS_INIT";
export const GET_FORECASTS_SUCCESS = "GET_FORECASTS_SUCCESS";
export const GET_FORECASTS_FAIL = "GET_FORECASTS_FAIL";

// PICTURE
export const GET_PICTURE_INIT = "GET_PICTURE_INIT";
export const GET_PICTURE_SUCCESS = "GET_PICTURE_SUCCESS";
export const GET_PICTURE_FAIL = "GET_PICTURE_FAIL";
